# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/benn/CODE/QtComms

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/benn/CODE/QtComms

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/benn/CODE/QtComms/CMakeFiles /home/benn/CODE/QtComms//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/benn/CODE/QtComms/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named protogen

# Build rule for target.
protogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 protogen
.PHONY : protogen

# fast build rule for target.
protogen/fast:
	$(MAKE) $(MAKESILENT) -f proto/CMakeFiles/protogen.dir/build.make proto/CMakeFiles/protogen.dir/build
.PHONY : protogen/fast

#=============================================================================
# Target rules for targets named protogen_autogen

# Build rule for target.
protogen_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 protogen_autogen
.PHONY : protogen_autogen

# fast build rule for target.
protogen_autogen/fast:
	$(MAKE) $(MAKESILENT) -f proto/CMakeFiles/protogen_autogen.dir/build.make proto/CMakeFiles/protogen_autogen.dir/build
.PHONY : protogen_autogen/fast

#=============================================================================
# Target rules for targets named zmqComms

# Build rule for target.
zmqComms: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zmqComms
.PHONY : zmqComms

# fast build rule for target.
zmqComms/fast:
	$(MAKE) $(MAKESILENT) -f comms/zeromq/CMakeFiles/zmqComms.dir/build.make comms/zeromq/CMakeFiles/zmqComms.dir/build
.PHONY : zmqComms/fast

#=============================================================================
# Target rules for targets named zmqComms_autogen

# Build rule for target.
zmqComms_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zmqComms_autogen
.PHONY : zmqComms_autogen

# fast build rule for target.
zmqComms_autogen/fast:
	$(MAKE) $(MAKESILENT) -f comms/zeromq/CMakeFiles/zmqComms_autogen.dir/build.make comms/zeromq/CMakeFiles/zmqComms_autogen.dir/build
.PHONY : zmqComms_autogen/fast

#=============================================================================
# Target rules for targets named controlGui

# Build rule for target.
controlGui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 controlGui
.PHONY : controlGui

# fast build rule for target.
controlGui/fast:
	$(MAKE) $(MAKESILENT) -f control/CMakeFiles/controlGui.dir/build.make control/CMakeFiles/controlGui.dir/build
.PHONY : controlGui/fast

#=============================================================================
# Target rules for targets named controlGui_autogen

# Build rule for target.
controlGui_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 controlGui_autogen
.PHONY : controlGui_autogen

# fast build rule for target.
controlGui_autogen/fast:
	$(MAKE) $(MAKESILENT) -f control/CMakeFiles/controlGui_autogen.dir/build.make control/CMakeFiles/controlGui_autogen.dir/build
.PHONY : controlGui_autogen/fast

#=============================================================================
# Target rules for targets named backend

# Build rule for target.
backend: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 backend
.PHONY : backend

# fast build rule for target.
backend/fast:
	$(MAKE) $(MAKESILENT) -f backend/CMakeFiles/backend.dir/build.make backend/CMakeFiles/backend.dir/build
.PHONY : backend/fast

#=============================================================================
# Target rules for targets named backend_autogen

# Build rule for target.
backend_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 backend_autogen
.PHONY : backend_autogen

# fast build rule for target.
backend_autogen/fast:
	$(MAKE) $(MAKESILENT) -f backend/CMakeFiles/backend_autogen.dir/build.make backend/CMakeFiles/backend_autogen.dir/build
.PHONY : backend_autogen/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... backend_autogen"
	@echo "... controlGui_autogen"
	@echo "... protogen_autogen"
	@echo "... zmqComms_autogen"
	@echo "... backend"
	@echo "... controlGui"
	@echo "... protogen"
	@echo "... zmqComms"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

